name 'cloudflair'
maintainer 'Anthony Neto'
maintainer_email 'anthony.neto@gmail.com'
license 'MIT'
description 'Installs/Configures cloudflair'
version '0.1.0'
issues_url 'https://github.com/anthonyneto/cookbook-cloudflair/issues'
source_url 'https://github.com/anthonyneto/cookbook-cloudflair'
